// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoCcfYMNAQ2ox4J6fkw1A45RtGhKR7ws',
    appId: '1:6489584827:web:31b5c5ef58cd296d97e59e',
    messagingSenderId: '6489584827',
    projectId: 'deprem-harita-e27f2',
    authDomain: 'deprem-harita-e27f2.firebaseapp.com',
    storageBucket: 'deprem-harita-e27f2.appspot.com',
    measurementId: 'G-RYBFZTFTJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKev5XzWg1Z2QYvy6RG3Jwe9HQ6dufQI',
    appId: '1:6489584827:android:06279a207759bc8697e59e',
    messagingSenderId: '6489584827',
    projectId: 'deprem-harita-e27f2',
    storageBucket: 'deprem-harita-e27f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTXLSBt6yQUmGDhkxGE9xHrfvnzxYZ7M',
    appId: '1:6489584827:ios:24c7855dc39d0bc797e59e',
    messagingSenderId: '6489584827',
    projectId: 'deprem-harita-e27f2',
    storageBucket: 'deprem-harita-e27f2.appspot.com',
    iosBundleId: 'com.example.depremharita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTXLSBt6yQUmGDhkxGE9xHrfvnzxYZ7M',
    appId: '1:6489584827:ios:1fc15063e7fafadd97e59e',
    messagingSenderId: '6489584827',
    projectId: 'deprem-harita-e27f2',
    storageBucket: 'deprem-harita-e27f2.appspot.com',
    iosBundleId: 'com.example.depremharita.RunnerTests',
  );
}
